gMoveDescription_Pound::
	.string "A physical attack\ndelivered with a\nlong tail or a\nforeleg, etc.$"

gMoveDescription_KarateChop:: @ 8482874
	.string "The foe is attacked\nwith a sharp chop.\nIt has a high\ncritical-hit ratio.$"

gMoveDescription_DoubleSlap:: @ 84828BD
	.string "The foe is slapped\nrepeatedly, back\nand forth, two to\nfive times.$"

gMoveDescription_CometPunch:: @ 84828FF
	.string "The foe is hit with\na flurry of punches\nthat strike two to\nfive times.$"

gMoveDescription_MegaPunch:: @ 8482946
	.string "The foe is slugged\nby a punch thrown\nwith muscle-packed\npower.$"

gMoveDescription_PayDay:: @ 8482985
	.string "Numerous coins are\nhurled at the foe.\nMoney is earned\nafter battle.$"

gMoveDescription_FirePunch:: @ 84829C9
	.string "The foe is punched\nwith a fiery fist.\nIt may leave the\nfoe with a burn.$"

gMoveDescription_IcePunch:: @ 8482A11
	.string "The foe is punched\nwith an icy fist.\nIt may leave the\nfoe frozen.$"

gMoveDescription_ThunderPunch:: @ 8482A53
	.string "The foe is punched\nwith an electrified\nfist. It may leave\nthe foe paralyzed.$"

gMoveDescription_Scratch:: @ 8482AA0
	.string "Hard, pointed, and\nsharp claws rake\nthe foe.$"

gMoveDescription_ViceGrip:: @ 8482ACD
	.string "Huge, impressive\npincers grip and\nsqueeze the foe.$"

gMoveDescription_Guillotine:: @ 8482B00
	.string "A vicious tearing\nattack with pincers.\nThe foe will faint\nif it hits.$"

gMoveDescription_RazorWind:: @ 8482B46
	.string "Blades of wind hit\nthe foe on the 2nd\nturn. It has a high\ncritical-hit ratio.$"

gMoveDescription_SwordsDance:: @ 8482B94
	.string "A frenetic dance of\nfighting. It sharply\nraises the ATTACK\nstat.$"

gMoveDescription_Cut:: @ 8482BD5
	.string "A basic attack.\nIt can be used to\ncut down thin trees\nand grass.\nIts power increases\nagainst grass types.$"

gMoveDescription_Gust:: @ 8482C16
	.string "Strikes the foe\nwith a gust of wind\nwhipped up by\nwings.$"

gMoveDescription_WingAttack:: @ 8482C4F
	.string "The foe is struck\nwith large, imposing\nwings spread wide.$"

gMoveDescription_Whirlwind:: @ 8482C89
	.string "The foe is made to\nswitch out with an\nally. In the wild,\nthe battle ends.$"

gMoveDescription_Fly:: @ 8482CD3
	.string "A 2-turn move that\nhits on the 2nd\nturn. Use it to fly\nto any known town.$"

gMoveDescription_Bind:: @ 8482D1D
	.string "A long body or\ntentacles are used\nto bind the foe for\ntwo to five turns.$"

gMoveDescription_Slam:: @ 8482D66
	.string "The foe is struck\nwith a long tail,\nvines, etc.$"

gMoveDescription_VineWhip:: @ 8482D96
	.string "The foe is struck\nwith slender, whip-\nlike vines.$"

gMoveDescription_Stomp:: @ 8482DC8
	.string "The foe is stomped\nwith a big foot.\nIt may make the\nfoe flinch.$"

gMoveDescription_DoubleKick:: @ 8482E08
	.string "Two legs are used\nto quickly kick the\nfoe twice in one\nturn.$"

gMoveDescription_MegaKick:: @ 8482E45
	.string "The foe is attacked\nby a kick fired\nwith muscle-packed\npower.$"

gMoveDescription_JumpKick:: @ 8482E83
	.string "The user jumps up\nhigh, then kicks.\nIf it misses, the\nuser hurts itself.$"

gMoveDescription_RollingKick:: @ 8482ECC
	.string "A quick kick from a\nrolling spin.\nIt may make the\nfoe flinch.$"

gMoveDescription_SandAttack:: @ 8482F0A
	.string "A lot of sand is\nhurled in the foe's\nface, reducing its\naccuracy.$"

gMoveDescription_Headbutt:: @ 8482F4C
	.string "The user sticks its\nhead out and rams.\nIt may make the\nfoe flinch.$"

gMoveDescription_HornAttack:: @ 8482F8F
	.string "The foe is jabbed\nwith a sharply\npointed horn to\ninflict damage.$"

gMoveDescription_FuryAttack:: @ 8482FD0
	.string "The foe is jabbed\nrepeatedly with a\nhorn or beak two to\nfive times.$"

gMoveDescription_HornDrill:: @ 8483014
	.string "The horn is rotated\nlike a drill to ram.\nThe foe will faint\nif it hits.$"

gMoveDescription_Tackle:: @ 848305C
	.string "A physical attack\nin which the user\ncharges, full body,\ninto the foe.$"

gMoveDescription_BodySlam:: @ 84830A2
	.string "The user drops its\nfull body on the\nfoe. It may leave\nthe foe paralyzed.$"

gMoveDescription_Wrap:: @ 84830EB
	.string "A long body or\nvines are used to\nwrap the foe for\ntwo to five turns.$"

gMoveDescription_TakeDown:: @ 8483130
	.string "A reckless, full-\nbody charge attack\nthat also hurts the\nuser a little.$"

gMoveDescription_Thrash:: @ 8483178
	.string "The user rampages\nabout for two to\nthree turns, then\nbecomes confused.$"

gMoveDescription_DoubleEdge:: @ 84831BF
	.string "A reckless, life-\nrisking tackle that\nalso hurts the user\na little.$"

gMoveDescription_TailWhip:: @ 8483203
	.string "The user wags its\ntail cutely, making\nthe foe lower its\nDEFENSE stat.$"

gMoveDescription_PoisonSting:: @ 8483249
	.string "The foe is stabbed\nwith a toxic barb,\netc. It may poison\nthe foe.$"

gMoveDescription_Twineedle:: @ 848328B
	.string "The foe is stabbed\ntwice with foreleg\nstingers. It may\npoison the foe.$"

gMoveDescription_PinMissile:: @ 84832D2
	.string "Sharp pins are shot\nat the foe and hit\ntwo to five times\nat once.$"

gMoveDescription_Leer:: @ 8483314
	.string "The foe is given an\nintimidating look\nthat lowers its\nDEFENSE stat.$"

gMoveDescription_Bite:: @ 8483358
	.string "The user bites with\nvicious fangs.\nIt may make the\nfoe flinch.$"

gMoveDescription_Growl:: @ 8483397
	.string "The user growls in\na cute way, making\nthe foe lower its\nATTACK stat.$"

gMoveDescription_Roar:: @ 84833DC
	.string "The foe is made to\nswitch out with an\nally. In the wild,\nthe battle ends.$"

gMoveDescription_Sing:: @ 8483426
	.string "A soothing song\nin a calming voice\nlulls the foe into\na deep slumber.$"

gMoveDescription_Supersonic:: @ 848346C
	.string "The user generates\nodd sound waves.\nIt may confuse the\nfoe.$"

gMoveDescription_SonicBoom:: @ 84834A8
	.string "The foe is hit with\na shock wave that\nalways inflicts 20-\nHP damage.$"

gMoveDescription_Disable:: @ 84834ED
	.string "For a few turns,\nit prevents the foe\nfrom using the move\nit last used.$"

gMoveDescription_Acid:: @ 8483534
	.string "The foe is sprayed\nwith a harsh, hide-\nmelting acid that\nmay lower DEFENSE.$"

gMoveDescription_Ember:: @ 8483580
	.string "The foe is attacked\nwith small flames.\nThe foe may suffer\na burn.$"

gMoveDescription_Flamethrower:: @ 84835C2
	.string "The foe is scorched\nwith intense flames.\nThe foe may suffer\na burn.$"

gMoveDescription_Mist:: @ 8483606
	.string "The ally party is\nprotected by a\nmist that prevents\nstat reductions.$"

gMoveDescription_WaterGun:: @ 848364B
	.string "The foe is struck\nwith a lot of water\nexpelled forcibly\nfrom the mouth.$"

gMoveDescription_HydroPump:: @ 8483693
	.string "A high volume of\nwater is blasted at\nthe foe under great\npressure.$"

gMoveDescription_Surf:: @ 84836D6
	.string "A big wave crashes\ndown on the foe.\nCan also be used\nfor crossing water.$"

gMoveDescription_IceBeam:: @ 848371F
	.string "The foe is struck\nwith an icy beam.\nIt may freeze the\nfoe solid.$"

gMoveDescription_Blizzard:: @ 8483760
	.string "The foe is blasted\nwith a blizzard.\nIt may freeze the\nfoe solid.$"

gMoveDescription_Psybeam:: @ 84837A1
	.string "A peculiar ray is\nshot at the foe.\nIt may leave the\nfoe confused.$"

gMoveDescription_BubbleBeam:: @ 84837E3
	.string "A spray of bubbles\nstrikes the foe.\nIt may lower the\nfoe's SPEED stat.$"

gMoveDescription_AuroraBeam:: @ 848382A
	.string "A rainbow-colored\nattack beam.\nIt may lower the\nfoe's ATTACK stat.$"

gMoveDescription_HyperBeam:: @ 848386D
	.string "A severely damaging\nattack that makes\nthe user rest on\nthe next turn.$"

gMoveDescription_Peck:: @ 84838B3
	.string "The foe is jabbed\nwith a sharply\npointed beak or\nhorn.$"

gMoveDescription_DrillPeck:: @ 84838EA
	.string "A corkscrewing\nattack with the\nsharp beak acting\nas a drill.$"

gMoveDescription_Submission:: @ 8483927
	.string "A reckless, full-\nbody throw attack\nthat also hurts the\nuser a little.$"

gMoveDescription_LowKick:: @ 848396E
	.string "A low, tripping kick\nthat inflicts more\ndamage on heavier\nfoes.$"

gMoveDescription_Counter:: @ 84839AE
	.string "A retaliation move\nthat counters any\nphysical hit with\ndouble the damage.$"

gMoveDescription_SeismicToss:: @ 84839F8
	.string "A gravity-fed throw\nthat causes damage\nmatching the user's\nlevel.$"

gMoveDescription_Strength:: @ 8483A3A
	.string "The user raises\nits ATK stat,\nthen slugs the foe\nat maximum power.$"

gMoveDescription_Absorb:: @ 8483A82
	.string "An attack that\nabsorbs half the\ndamage it inflicted\nto restore HP.$"

gMoveDescription_MegaDrain:: @ 8483AC5
	.string "A tough attack that\ndrains half the\ndamage it inflicted\nto restore HP.$"

gMoveDescription_LeechSeed:: @ 8483B0C
	.string "A seed is planted\non the foe to steal\nsome HP for the \nuser on every turn.$"

gMoveDescription_Growth:: @ 8483B57
	.string "The user's body is\nforced to grow,\nraising the SP.\nATK stat.$"

gMoveDescription_RazorLeaf:: @ 8483B94
	.string "The foe is hit with\na cutting leaf.\nIt has a high\ncritical-hit ratio.$"

gMoveDescription_SolarBeam:: @ 8483BDA
	.string "A 2-turn move that\nblasts the foe with\nabsorbed energy in\nthe 2nd turn.$"

gMoveDescription_PoisonPowder:: @ 8483C22
	.string "A cloud of toxic\ndust is scattered.\nIt may poison the\nfoe.$"

gMoveDescription_StunSpore:: @ 8483C5D
	.string "Paralyzing dust is\nscattered wildly.\nIt may paralyze\nthe foe.$"

gMoveDescription_SleepPowder:: @ 8483C9B
	.string "A sleep-inducing\ndust is scattered\nin high volume\naround a foe.$"

gMoveDescription_PetalDance:: @ 8483CDB
	.string "The user attacks\nwith petals for two\nto three turns,\nthen gets confused.$"

gMoveDescription_StringShot:: @ 8483D24
	.string "The foe is bound\nwith strings shot\nfrom the mouth to\nreduce its SPEED.$"

gMoveDescription_DragonRage:: @ 8483D6B
	.string "The foe is hit with\na shock wave that\nalways inflicts 40-\nHP damage.$"

gMoveDescription_FireSpin:: @ 8483DB0
	.string "The foe is trapped\nin an intense spiral\nof fire that rages\ntwo to five turns.$"

gMoveDescription_ThunderShock:: @ 8483DFE
	.string "An electric shock\nattack that may\nalso leave the foe\nparalyzed.$"

gMoveDescription_Thunderbolt:: @ 8483E3E
	.string "A strong electrical\nattack that may\nalso leave the foe\nparalyzed.$"

gMoveDescription_ThunderWave:: @ 8483E80
	.string "A weak electric\nshock that is sure\nto cause paralysis\nif it hits.$"

gMoveDescription_Thunder:: @ 8483EC2
	.string "A brutal lightning\nattack that may\nalso leave the foe\nparalyzed.$"

gMoveDescription_RockThrow:: @ 8483F03
	.string "The foe is attacked\nwith a shower of\nsmall, easily\nthrown rocks.$"

gMoveDescription_Earthquake:: @ 8483F44
	.string "An earthquake that\nstrikes all POKéMON\nin battle excluding\nthe user.$"

gMoveDescription_Fissure:: @ 8483F89
	.string "The foe is dropped\ninto a fissure.\nThe foe faints if it\nhits.$"

gMoveDescription_Dig:: @ 8483FC7
	.string "An attack that hits\non the 2nd turn.\nCan also be used\nto exit dungeons.$"

gMoveDescription_Toxic:: @ 848400F
	.string "A move that badly\npoisons the foe.\nIts poison damage\nworsens every turn.$"

gMoveDescription_Confusion:: @ 8484058
	.string "A weak telekinetic\nattack that may\nalso leave the foe\nconfused.$"

gMoveDescription_Psychic:: @ 8484098
	.string "A strong telekinetic\nattack. It may also\nlower the foe's\nSP. DEF stat.$"

gMoveDescription_Hypnosis:: @ 84840DF
	.string "Hypnotic suggestion\nis used to make the\nfoe fall into a\ndeep sleep.$"

gMoveDescription_Meditate:: @ 8484123
	.string "The user meditates\nto awaken its power\nand raise its\nATTACK stat.$"

gMoveDescription_Agility:: @ 8484165
	.string "The user relaxes\nand lightens its\nbody to sharply\nboost its SPEED.$"

gMoveDescription_QuickAttack:: @ 84841A8
	.string "An almost invisibly\nfast attack that\nis certain to strike\nfirst.$"

gMoveDescription_Rage:: @ 84841E9
	.string "An attack that\nbecomes stronger\neach time the user\nis hit in battle.$"

gMoveDescription_Teleport:: @ 848422E
	.string "Use it to flee from\nany wild POKéMON.\nAlso warps to the\nlast POKé CENTER.$"

gMoveDescription_NightShade:: @ 8484278
	.string "An attack with a\nmirage that inflicts\ndamage matching\nthe user's level.$"

gMoveDescription_Mimic:: @ 84842C0
	.string "The user copies the\nmove last used by\nthe foe for the\nrest of the battle.$"

gMoveDescription_Screech:: @ 848430A
	.string "An ear-splitting\nscreech is emitted\nto sharply reduce\nthe foe's DEFENSE.$"

gMoveDescription_DoubleTeam:: @ 8484353
	.string "The user creates\nillusory copies of\nitself to raise its\nevasiveness.$"

gMoveDescription_Recover:: @ 8484398
	.string "A self-healing move\nthat restores HP by\nup to half of the\nuser's maximum HP.$"

gMoveDescription_Harden:: @ 84843E5
	.string "The user stiffens\nall the muscles in\nits body to raise\nits DEFENSE stat.$"

gMoveDescription_Minimize:: @ 848442E
	.string "The user compresses\nall the cells in its\nbody to raise its\nevasiveness.$"

gMoveDescription_Smokescreen:: @ 8484476
	.string "An obscuring cloud\nof smoke or ink\nreduces the foe's\naccuracy.$"

gMoveDescription_ConfuseRay:: @ 84844B5
	.string "The foe is exposed\nto a sinister ray\nthat triggers\nconfusion.$"

gMoveDescription_Withdraw:: @ 84844F3
	.string "The user withdraws\nits body in its hard\nshell, raising its\nDEFENSE stat.$"

gMoveDescription_DefenseCurl:: @ 848453C
	.string "The user curls up\nto conceal weak\nspots and raise its\nDEFENSE stat.$"

gMoveDescription_Barrier:: @ 8484580
	.string "The user creates a\nsturdy wall that\nsharply raises its\nDEFENSE stat.$"

gMoveDescription_LightScreen:: @ 84845C5
	.string "A wall of light\ncuts damage from\nSP. ATK attacks\nfor five turns.$"

gMoveDescription_Haze:: @ 8484606
	.string "Eliminates all stat\nchanges among all\nPOKéMON engaged in\nbattle.$"

gMoveDescription_Reflect:: @ 8484647
	.string "A wall of light\ncuts damage from\nphysical attacks\nfor five turns.$"

gMoveDescription_FocusEnergy:: @ 8484689
	.string "The user takes a\ndeep breath and\nfocuses to raise its\ncritical-hit ratio.$"

gMoveDescription_Bide:: @ 84846D3
	.string "The user endures\nattacks for two\nturns, then strikes\nback double.$"

gMoveDescription_Metronome:: @ 8484715
	.string "Waggles a finger\nand stimulates the\nbrain into using any\nmove at random.$"

gMoveDescription_MirrorMove:: @ 848475E
	.string "The user counters\nthe move last used\nby the foe with the\nsame move.$"

gMoveDescription_SelfDestruct:: @ 84847A2
	.string "The user blows up\nto inflict severe\ndamage, even\nmaking itself faint.$"

gMoveDescription_EggBomb:: @ 84847E8
	.string "A large egg is\nhurled with great\nforce at the foe to\ninflict damage.$"

gMoveDescription_Lick:: @ 848482D
	.string "The foe is licked\nand hit with a long\ntongue. It may\nalso paralyze.$"

gMoveDescription_Smog:: @ 8484871
	.string "The foe is attacked\nwith exhaust gases.\nIt may also poison\nthe foe.$"

gMoveDescription_Sludge:: @ 84848B5
	.string "Toxic sludge is\nhurled at the foe.\nIt may poison the\ntarget.$"

gMoveDescription_BoneClub:: @ 84848F2
	.string "The foe is clubbed\nwith a bone held in\nhand. It may make\nthe foe flinch.$"

gMoveDescription_FireBlast:: @ 848493B
	.string "The foe is hit with\nan intense flame.\nIt may leave the\ntarget with a burn.$"

gMoveDescription_Waterfall:: @ 8484986
	.string "A powerful charge\nattack. It can also\nbe used to climb\na waterfall.$"

gMoveDescription_Clamp:: @ 84849CA
	.string "The foe is clamped\nand squeezed by\nthe user's shell for\ntwo to five turns.$"

gMoveDescription_Swift:: @ 8484A15
	.string "Star-shaped rays\nthat never miss are\nfired at all foes in\nbattle.$"

gMoveDescription_SkullBash:: @ 8484A57
	.string "The user raises its\nDEFENSE in the 1st\nturn, then attacks\nin the 2nd turn.$"

gMoveDescription_SpikeCannon:: @ 8484AA2
	.string "Sharp spikes are\nfired at the foe to\nstrike two to five\ntimes.$"

gMoveDescription_Constrict:: @ 8484AE1
	.string "The foe is attacked\nwith long tentacles\nor vines. It may\nlower SPEED.$"

gMoveDescription_Amnesia:: @ 8484B27
	.string "Forgets about\nsomething and\nsharply raises\nSP. DEF.$"

gMoveDescription_Kinesis:: @ 8484B5B
	.string "The user distracts\nthe foe by bending\na spoon. It may\nlower accuracy.$"

gMoveDescription_SoftBoiled:: @ 8484BA1
	.string "Heals the user by\nup to half its full\nHP. It can be used\nto heal an ally.$"

gMoveDescription_HiJumpKick:: @ 8484BEB
	.string "A strong jumping\nknee kick. If it\nmisses, the user is\nhurt.$"

gMoveDescription_Glare:: @ 8484C27
	.string "The user intimidates\nthe foe with the\ndesign on its belly\nto cause paralysis.$"

gMoveDescription_DreamEater:: @ 8484C75
	.string "Absorbs half the\ndamage it inflicted\non a sleeping foe\nto restore HP.$"

gMoveDescription_PoisonGas:: @ 8484CBB
	.string "The foe is sprayed\nwith a cloud of\ntoxic gas that may\npoison the foe.$"

gMoveDescription_Barrage:: @ 8484D01
	.string "Round objects are\nhurled at the foe\nto strike two to\nfive times.$"

gMoveDescription_LeechLife:: @ 8484D42
	.string "An attack that\nabsorbs half the\ndamage it inflicted\nto restore HP.$"

gMoveDescription_LovelyKiss:: @ 8484D85
	.string "The user forces a\nkiss on the foe\nwith a scary face\nthat induces sleep.$"

gMoveDescription_SkyAttack:: @ 8484DCD
	.string "A 2nd-turn attack\nmove with a high\ncritical-hit ratio.\nThe foe may flinch.$"

gMoveDescription_Transform:: @ 8484E18
	.string "The user transforms\ninto a copy of the\nfoe with even the\nsame move set.$"

gMoveDescription_Bubble:: @ 8484E60
	.string "A spray of bubbles\nhits the foe.\nIt may lower the\nfoe's SPEED stat.$"

gMoveDescription_DizzyPunch:: @ 8484EA4
	.string "The foe is hit with\na rhythmic punch\nthat may leave it\nconfused.$"

gMoveDescription_Spore:: @ 8484EE5
	.string "The user scatters\nbursts of fine\nspores that induce\nsleep.$"

gMoveDescription_Flash:: @ 8484F20
	.string "A blast of light\nthat cuts the foe's\naccuracy. It also\nmay cause flinch.$"

gMoveDescription_Psywave:: @ 8484F6A
	.string "The foe is attacked\nwith an odd, hot\nenergy wave that\nvaries greatly in intensity.$"

gMoveDescription_Splash:: @ 8484FB5
	.string "The user just flops\nand splashes around\nwithout having any\neffect.$"

gMoveDescription_AcidArmor:: @ 8484FF8
	.string "The user alters its\ncells to liquefy\nitself and sharply\nraise DEFENSE.$"

gMoveDescription_Crabhammer:: @ 848503F
	.string "A large pincer is\nused to hammer the\nfoe. It has a high\ncritical-hit ratio.$"

gMoveDescription_Explosion:: @ 848508B
	.string "The user explodes\nto inflict terrible\ndamage even while\nfainting itself.$"

gMoveDescription_FurySwipes:: @ 84850D4
	.string "The foe is raked\nwith sharp claws or\nscythes two to five\ntimes.$"

gMoveDescription_Bonemerang:: @ 8485114
	.string "The user throws a\nbone that hits the\nfoe once, then once\nagain on return.$"

gMoveDescription_Rest:: @ 848515E
	.string "The user sleeps for\ntwo turns to fully\nrestore HP and heal\nany status problem.$"

gMoveDescription_RockSlide:: @ 84851AD
	.string "Large boulders are\nhurled at the foe.\nIt may make the\nfoe flinch.$"

gMoveDescription_HyperFang:: @ 84851EF
	.string "The foe is attacked\nwith sharp fangs.\nIt may make the\nfoe flinch.$"

gMoveDescription_Sharpen:: @ 8485231
	.string "The user reduces\nits polygon count\nto sharpen edges\nand raise ATTACK.$"

gMoveDescription_Conversion:: @ 8485277
	.string "The user changes\nits type to match\nthe type of one of\nits moves.$"

gMoveDescription_TriAttack:: @ 84852B8
	.string "A simultaneous\n3-beam attack that\nmay paralyze, burn,\nor freeze the foe.$"

gMoveDescription_SuperFang:: @ 8485301
	.string "The user attacks\nwith sharp fangs\nand halves the\nfoe's HP.$"

gMoveDescription_Slash:: @ 848533C
	.string "The foe is slashed\nwith claws, etc.\nIt has a high\ncritical-hit ratio.$"

gMoveDescription_Substitute:: @ 8485382
	.string "The user creates a\ndecoy using one-\nquarter of its full\nHP.$"

gMoveDescription_Struggle:: @ 84853BE
	.string "An attack that is\nused only if there\nis no PP. It also\nhurts the user.$"

gMoveDescription_Sketch:: @ 8485405
	.string "This move copies\nthe move last used\nby the foe, then\ndisappears.$"

gMoveDescription_TripleKick:: @ 8485446
	.string "A 3-kick attack\nthat becomes more\npowerful with each\nsuccessive hit.$"

gMoveDescription_Thief:: @ 848548B
	.string "An attack that may\ntake the foe's held\nitem if the user\nisn't holding one.$"

gMoveDescription_SpiderWeb:: @ 84854D6
	.string "Ensnares the foe \nwith sticky string\nso it doesn't flee\nor switch out.$"

gMoveDescription_MindReader:: @ 848551D
	.string "The user predicts\nthe foe's action to\nensure its next\nattack hits.$"

gMoveDescription_Nightmare:: @ 8485560
	.string "A sleeping foe is\nshown a nightmare\nthat inflicts some\ndamage every turn.$"

gMoveDescription_FlameWheel:: @ 84855AA
	.string "The user makes a\nfiery charge at the\nfoe. It may cause\na burn.$"

gMoveDescription_Snore:: @ 84855E9
	.string "An attack that can\nbe used only while\nasleep. It may\ncause flinching.$"

gMoveDescription_Curse:: @ 848562F
	.string "A move that works\ndifferently for the\nGHOST-type and all\nthe other types.$"

gMoveDescription_Flail:: @ 8485679
	.string "A desperate attack\nthat becomes more\npowerful the less\nHP the user has.$"

gMoveDescription_Conversion2:: @ 84856C1
	.string "The user changes\ntype to make itself\nresistant to the\nlast attack it took.$"

gMoveDescription_Aeroblast:: @ 848570C
	.string "A vortex of air is\nshot at the foe.\nIt has a high\ncritical-hit ratio.$"

gMoveDescription_CottonSpore:: @ 8485752
	.string "Cotton-like spores\ncling to the foe,\nsharply reducing\nits SPEED stat.$"

gMoveDescription_Reversal:: @ 8485798
	.string "An all-out attack\nthat becomes more\npowerful the less\nHP the user has.$"

gMoveDescription_Spite:: @ 84857DF
	.string "A move that cuts\n2 to 5 PP from the\nmove last used by\nthe foe.$"

gMoveDescription_PowderSnow:: @ 848581E
	.string "Blasts the foe with\na snowy gust.\nIt may cause\nfreezing.$"

gMoveDescription_Protect:: @ 8485857
	.string "Enables the user to\nevade all attacks.\nIt may fail if used\nin succession.$"

gMoveDescription_MachPunch:: @ 84858A1
	.string "A punch thrown at\nblinding speed.\nIt is certain to\nstrike first.$"

gMoveDescription_ScaryFace:: @ 84858E2
	.string "Frightens the foe\nwith a scary face\nto sharply reduce\nits SPEED.$"

gMoveDescription_FaintAttack:: @ 8485923
	.string "The user draws up\nclose to the foe\ndisarmingly, then\nhits without fail.$"

gMoveDescription_SweetKiss:: @ 848596B
	.string "The user kisses\nthe foe with sweet\ncuteness that\ncauses confusion.$"

gMoveDescription_BellyDrum:: @ 84859AE
	.string "The user maximizes\nits ATTACK stat at\nthe cost of half\nits full HP.$"

gMoveDescription_SludgeBomb:: @ 84859F2
	.string "Filthy sludge is\nhurled at the foe.\nIt may poison the\ntarget.$"

gMoveDescription_MudSlap:: @ 8485A30
	.string "Mud is hurled in\nthe foe's face to\ninflict damage and\nlower its accuracy.$"

gMoveDescription_Octazooka:: @ 8485A7A
	.string "Ink is blasted in\nthe foe's face or\neyes to damage and\nlower accuracy.$"

gMoveDescription_Spikes:: @ 8485AC1
	.string "A trap of spikes is\nlaid around the\nfoe's party to hurt\nfoes switching in.$"

gMoveDescription_ZapCannon:: @ 8485B0C
	.string "An electric blast is\nfired like a cannon\nto inflict damage\nand paralyze.$"

gMoveDescription_Foresight:: @ 8485B55
	.string "Completely negates\nthe foe's efforts to\nheighten its ability\nto evade.$"

gMoveDescription_DestinyBond:: @ 8485B9C
	.string "If the user faints,\nthe foe delivering\nthe final hit also\nfaints.$"

gMoveDescription_PerishSong:: @ 8485BDE
	.string "Any battler that\nhears this faints\nin three turns\nunless it switches.$"

gMoveDescription_IcyWind:: @ 8485C24
	.string "A chilling wind is\nused to attack.\nIt also lowers the\nSPEED stat.$"

gMoveDescription_Detect:: @ 8485C66
	.string "Enables the user to\nevade all attacks.\nIt may fail if used\nin succession.$"

gMoveDescription_BoneRush:: @ 8485CB0
	.string "The user strikes\nthe foe with a bone\nin hand two to five\ntimes.$"

gMoveDescription_LockOn:: @ 8485CF0
	.string "The user locks on\nto the foe, making\nthe next move sure\nto hit.$"

gMoveDescription_Outrage:: @ 8485D30
	.string "The user thrashes\nabout for two to\nthree turns, then\nbecomes confused.$"

gMoveDescription_Sandstorm:: @ 8485D77
	.string "A 5-turn sandstorm\nthat damages all\ntypes except ROCK,\nGROUND, and STEEL.$"

gMoveDescription_GigaDrain:: @ 8485DC1
	.string "A harsh attack that\nabsorbs half the\ndamage it inflicted\nto restore HP.$"

gMoveDescription_Endure:: @ 8485E09
	.string "The user endures\nany hit with 1 HP\nleft. It may fail if\nused in succession.$"

gMoveDescription_Charm:: @ 8485E55
	.string "The foe is charmed\nby the user's cute\nappeals, sharply\ncutting its ATTACK.$"

gMoveDescription_Rollout:: @ 8485EA0
	.string "A 5-turn rolling\nattack that becomes\nstronger each time\nit hits.$"

gMoveDescription_FalseSwipe:: @ 8485EE1
	.string "A restrained attack\nthat always leaves\nthe foe with at\nleast 1 HP.$"

gMoveDescription_Swagger:: @ 8485F24
	.string "A move that makes\nthe foe confused,\nbut also sharply\nraises its ATTACK.$"

gMoveDescription_MilkDrink:: @ 8485F6C
	.string "Heals the user by\nup to half its full\nHP. It can be used\nto heal an ally.$"

gMoveDescription_Spark:: @ 8485FB6
	.string "An electrically\ncharged tackle that\nmay also paralyze\nthe foe.$"

gMoveDescription_FuryCutter:: @ 8485FF5
	.string "An attack that\ngrows stronger on\neach successive\nhit.$"

gMoveDescription_SteelWing:: @ 848602B
	.string "The foe is hit with\nwings of steel.\nIt may also raise\nthe user's DEFENSE.$"

gMoveDescription_MeanLook:: @ 8486075
	.string "The foe is fixed\nwith a mean look\nthat prevents it\nfrom escaping.$"

gMoveDescription_Attract:: @ 84860B7
	.string "If it is the other\ngender, the foe is\nmade infatuated and\nunlikely to attack.$"

gMoveDescription_SleepTalk:: @ 8486105
	.string "While asleep, the\nuser randomly uses\none of the moves it\nknows.$"

gMoveDescription_HealBell:: @ 8486145
	.string "A soothing bell\nchimes to heal the\nstatus problems of\nall allies.$"

gMoveDescription_Return:: @ 8486187
	.string "This attack move\ngrows more powerful\nthe more the user\nlikes its TRAINER.$"

gMoveDescription_Present:: @ 84861D1
	.string "The foe is given a\nbooby-trapped gift.\nIt restores HP\nsometimes, however.$"

gMoveDescription_Frustration:: @ 848621B
	.string "This attack move\ngrows more powerful\nthe less the user\nlikes its TRAINER.$"

gMoveDescription_Safeguard:: @ 8486265
	.string "It protects the\nuser's party from\nall status problems\nfor five turns.$"

gMoveDescription_PainSplit:: @ 84862AB
	.string "The user adds its\nHP to the foe's HP,\nthen equally shares\nthe total HP.$"

gMoveDescription_SacredFire:: @ 84862F3
	.string "A mystical and\npowerful fire\nattack that may\ninflict a burn.$"

gMoveDescription_Magnitude:: @ 8486330
	.string "A ground-shaking\nattack against all\nstanding POKéMON.\nIts power varies.$"

gMoveDescription_DynamicPunch:: @ 8486378
	.string "The foe is punched\nwith the user's full\npower. It confuses\nthe foe if it hits.$"

gMoveDescription_Megahorn:: @ 84863C7
	.string "A brutal ramming\nattack delivered\nwith a tough and\nimpressive horn.$"

gMoveDescription_DragonBreath:: @ 848640B
	.string "The foe is hit with\nan incredible blast\nof breath that may\nalso paralyze.$"

gMoveDescription_BatonPass:: @ 8486455
	.string "The user switches\nout, passing along\nany stat changes\nto the new battler.$"

gMoveDescription_Encore:: @ 848649F
	.string "Makes the foe use\nthe move it last\nused repeatedly for\ntwo to six turns.$"

gMoveDescription_Pursuit:: @ 84864E8
	.string "An attack move that\nworks especially\nwell on a foe that\nis switching out.$"

gMoveDescription_RapidSpin:: @ 8486532
	.string "An attack that\nfrees the user from\nBIND, WRAP, LEECH\nSEED, and SPIKES.$"

gMoveDescription_SweetScent:: @ 8486579
	.string "Allures the foe to\nreduce evasiveness.\nIt also attracts\nwild POKéMON.$"

gMoveDescription_IronTail:: @ 84865BF
	.string "An attack with a\nsteel-hard tail.\nIt may lower the\nfoe's DEFENSE stat.$"

gMoveDescription_MetalClaw:: @ 8486606
	.string "The foe is attacked\nwith steel claws.\nIt may also raise\nthe user's ATTACK.$"

gMoveDescription_VitalThrow:: @ 8486651
	.string "Makes the user\nattack after the\nfoe. In return,\nit will not miss.$"

gMoveDescription_MorningSun:: @ 8486693
	.string "Restores the user's\nHP. The amount of\nHP regained varies\nwith the weather.$"

gMoveDescription_Synthesis:: @ 84866DE
	.string "Restores the user's\nHP. The amount of\nHP regained varies\nwith the weather.$"

gMoveDescription_Moonlight:: @ 8486729
	.string "Restores the user's\nHP. The amount of\nHP regained varies\nwith the weather.$"

gMoveDescription_HiddenPower:: @ 8486774
	.string "An attack that\nvaries in type and\nintensity depending\non the user.$"

gMoveDescription_CrossChop:: @ 84867B7
	.string "The foe is hit with\ndouble chops.\nIt has a high\ncritical-hit ratio.$"

gMoveDescription_Twister:: @ 84867FB
	.string "A vicious twister\nattacks the foe.\nIt may make the\nfoe flinch.$"

gMoveDescription_RainDance:: @ 848683A
	.string "A heavy rain falls\nfor five turns,\npowering up WATER-\ntype moves.$"

gMoveDescription_SunnyDay:: @ 848687C
	.string "The sun blazes for\nfive turns, powering\nup FIRE-type\nmoves.$"

gMoveDescription_Crunch:: @ 84868B8
	.string "The foe is crunched\nwith sharp fangs.\nIt may lower the\nfoe's SP. DEF.$"

gMoveDescription_MirrorCoat:: @ 84868FE
	.string "A retaliation move\nthat pays back the\nfoe's special attack\ndouble.$"

gMoveDescription_PsychUp:: @ 8486941
	.string "The user hypnotizes\nitself into copying\nany stat change\nmade by the foe.$"

gMoveDescription_ExtremeSpeed:: @ 848698A
	.string "A blindingly speedy\ncharge attack that\nalways goes before\nany other.$"

gMoveDescription_AncientPower:: @ 84869CF
	.string "An ancient power is\nused to attack. It\nmay also raise all\nthe user's stats.$"

gMoveDescription_ShadowBall:: @ 8486A1B
	.string "A shadowy blob is\nhurled at the foe.\nMay also lower the\nfoe's SP. DEF.$"

gMoveDescription_FutureSight:: @ 8486A62
	.string "Two turns after\nthis move is used,\nthe foe is attacked\npsychically.$"

gMoveDescription_RockSmash:: @ 8486AA6
	.string "An attack that may\nalso cut DEFENSE.\nIts power increases\nagainst rock types.$"

gMoveDescription_Whirlpool:: @ 8486AEF
	.string "The foe is trapped\nin a fast, vicious\nwhirlpool for two\nto five turns.$"

gMoveDescription_BeatUp:: @ 8486B36
	.string "All party POKéMON\njoin in the attack.\nThe more allies,\nthe more damage.$"

gMoveDescription_FakeOut:: @ 8486B7E
	.string "An attack that hits\nfirst and causes\nflinching. Usable\nonly on 1st turn.$"

gMoveDescription_Uproar:: @ 8486BC7
	.string "The user attacks in\nan uproar that\nprevents sleep for\ntwo to five turns.$"

gMoveDescription_Stockpile:: @ 8486C10
	.string "The user charges\nup power for use\nlater. It can be\nused three times.$"

gMoveDescription_SpitUp:: @ 8486C55
	.string "The power built\nusing STOCKPILE is\nreleased at once\nfor attack.$"

gMoveDescription_Swallow:: @ 8486C95
	.string "The energy it built\nusing STOCKPILE is\nabsorbed to restore\nHP.$"

gMoveDescription_HeatWave:: @ 8486CD4
	.string "The user exhales a\nheated breath to\nattack. It may also\ninflict a burn.$"

gMoveDescription_Hail:: @ 8486D1C
	.string "A hailstorm lasting\nfive turns damages\nall POKéMON except\nthe ICE-type.$"

gMoveDescription_Torment:: @ 8486D64
	.string "It enrages the foe,\nmaking it incapable\nof using the same\nmove successively.$"

gMoveDescription_Flatter:: @ 8486DB1
	.string "Flattery is used to\nconfuse the foe,\nbut its SP. ATK\nalso rises.$"

gMoveDescription_WillOWisp:: @ 8486DF2
	.string "A sinister, bluish\nwhite flame is shot\nat the foe to\ninflict a burn.$"

gMoveDescription_Memento:: @ 8486E37
	.string "The user faints,\nbut sharply lowers\nthe foe's ATTACK\nand SP. ATK.$"

gMoveDescription_Facade:: @ 8486E79
	.string "An attack that is\nboosted if user is\nburned, poisoned,\nor paralyzed.$"

gMoveDescription_FocusPunch:: @ 8486EBE
	.string "An attack that is\nexecuted last.\nThe user flinches\nif hit beforehand.$"

gMoveDescription_SmellingSalt:: @ 8486F04
	.string "Doubly effective on\na paralyzed foe,\nbut it also cures\nthe foe's paralysis.$"

gMoveDescription_FollowMe:: @ 8486F50
	.string "The user draws\nattention to itself,\nmaking foes attack\nonly the user.$"

gMoveDescription_NaturePower:: @ 8486F96
	.string "An attack that\nchanges type\ndepending on the\nuser's location.$"

gMoveDescription_Charge:: @ 8486FD4
	.string "The user charges\npower to boost the\nELECTRIC move it\nuses next.$"

gMoveDescription_Taunt:: @ 8487014
	.string "The foe is taunted\ninto a rage that\nallows it to use\nonly attack moves.$"

gMoveDescription_HelpingHand:: @ 848705C
	.string "A move that boosts\nthe power of the\nally's attack in a\nbattle.$"

gMoveDescription_Trick:: @ 848709B
	.string "A move that tricks\nthe foe into\ntrading held items\nwith the user.$"

gMoveDescription_RolePlay:: @ 84870DD
	.string "The user mimics the\nfoe completely and\ncopies the foe's\nability.$"

gMoveDescription_Wish:: @ 848711E
	.string "A self-healing move\nthat restores half\nthe full HP on the\nnext turn.$"

gMoveDescription_Assist:: @ 8487163
	.string "The user randomly\npicks and uses a\nmove of an allied\nPOKéMON.$"

gMoveDescription_Ingrain:: @ 84871A1
	.string "The user lays roots\nthat restore HP on\nevery turn.\nIt can't switch out.$"

gMoveDescription_Superpower:: @ 84871E9
	.string "A powerful attack,\nbut it also lowers\nthe user's ATTACK\nand DEFENSE stats.$"

gMoveDescription_MagicCoat:: @ 8487234
	.string "Reflects back the\nfoe's LEECH SEED\nand any status-\ndamaging move.$"

gMoveDescription_Recycle:: @ 8487276
	.string "A move that\nrecycles a used\nitem for use once\nmore.$"

gMoveDescription_Revenge:: @ 84872AA
	.string "An attack move that\ngains in intensity if\nthe target has hurt\nthe user.$"

gMoveDescription_BrickBreak:: @ 84872F2
	.string "An attack that also\nbreaks any barrier\nlike LIGHT SCREEN\nand REFLECT.$"

gMoveDescription_Yawn:: @ 8487338
	.string "A huge yawn lulls\nthe foe into falling\nasleep on the next\nturn.$"

gMoveDescription_KnockOff:: @ 8487378
	.string "Knocks down the\nfoe's held item to\nprevent its use\nduring the battle.$"

gMoveDescription_Endeavor:: @ 84873BE
	.string "Gains power the\nfewer HP the user\nhas compared with\nthe foe.$"

gMoveDescription_Eruption:: @ 84873FB
	.string "The higher the\nuser's HP, the more\npowerful this\nattack becomes.$"

gMoveDescription_SkillSwap:: @ 848743C
	.string "The user employs\nits psychic power\nto swap abilities\nwith the foe.$"

gMoveDescription_Imprison:: @ 848747F
	.string "Prevents foes from\nusing any move\nthat is also known\nby the user.$"

gMoveDescription_Refresh:: @ 84874C1
	.string "A self-healing move\nthat cures the user\nof a poisoning,\nburn, or paralysis.$"

gMoveDescription_Grudge:: @ 848750D
	.string "If the user faints,\nthis move deletes\nthe PP of the move\nthat finished it.$"

gMoveDescription_Snatch:: @ 8487558
	.string "Steals the effects\nof the foe's\nhealing or status-\nchanging move.$"

gMoveDescription_SecretPower:: @ 848759A
	.string "An attack that may\nhave an additional\neffect that varies\nwith the terrain.$"

gMoveDescription_Dive:: @ 84875E5
	.string "The user dives\nunderwater on the\nfirst turn and\nstrikes next turn.$"

gMoveDescription_ArmThrust:: @ 8487628
	.string "A quick flurry of\nstraight-arm\npunches that hit\ntwo to five times.$"

gMoveDescription_Camouflage:: @ 848766B
	.string "Alters the user's\ntype depending on\nthe location's\nterrain.$"

gMoveDescription_TailGlow:: @ 84876A7
	.string "The user flashes a\nlight that sharply\nraises its SP. ATK\nstat.$"

gMoveDescription_LusterPurge:: @ 84876E6
	.string "A burst of light\ninjures the foe. It\nmay also lower the\nfoe's SP. DEF.$"

gMoveDescription_MistBall:: @ 848772D
	.string "A flurry of down\nhits the foe. It\nmay also lower the\nfoe's SP. ATK.$"

gMoveDescription_FeatherDance:: @ 8487771
	.string "The foe is covered\nwith a mass of down\nthat sharply cuts\nthe ATTACK stat.$"

gMoveDescription_TeeterDance:: @ 84877BB
	.string "A wobbly dance\nthat confuses all\nthe POKéMON in\nbattle.$"

gMoveDescription_BlazeKick:: @ 84877F3
	.string "A fiery kick with a\nhigh critical-hit\nratio. It may also\nburn the foe.$"

gMoveDescription_MudSport:: @ 848783A
	.string "Weakens ELECTRIC-\ntype attacks while\nthe user is in the\nbattle.$"

gMoveDescription_IceBall:: @ 848787A
	.string "A 5-turn rolling\nattack that becomes\nstronger each time\nit rolls.$"

gMoveDescription_NeedleArm:: @ 84878BC
	.string "An attack using\nthorny arms.\nIt may make the\nfoe flinch.$"

gMoveDescription_SlackOff:: @ 84878F5
	.string "The user slacks off\nand restores its HP\nby half its full\nHP.$"

gMoveDescription_HyperVoice:: @ 8487932
	.string "The user lets loose\na horribly loud\nshout with the\npower to damage.$"

gMoveDescription_PoisonFang:: @ 8487976
	.string "The foe is bitten\nwith toxic fangs.\nIt may also badly\npoison the foe.$"

gMoveDescription_CrushClaw:: @ 84879BC
	.string "The foe is attacked\nwith sharp claws.\nIt may also lower\nthe foe's DEFENSE.$"

gMoveDescription_BlastBurn:: @ 8487A07
	.string "The foe is hit with\na huge explosion.\nThe user can't move\non the next turn.$"

gMoveDescription_HydroCannon:: @ 8487A53
	.string "The foe is hit with\na watery cannon.\nThe user can't move\non the next turn.$"

gMoveDescription_MeteorMash:: @ 8487A9E
	.string "The foe is hit with\na hard, fast punch.\nIt may also raise\nthe user's ATTACK.$"

gMoveDescription_Astonish:: @ 8487AEB
	.string "An attack using a\nstartling shout.\nIt also may make\nthe foe flinch.$"

gMoveDescription_WeatherBall:: @ 8487B2F
	.string "An attack that\nvaries in power and\ntype depending on\nthe weather.$"

gMoveDescription_Aromatherapy:: @ 8487B71
	.string "A soothing scent is\nreleased to heal\nall status problems\nin the user's party.$"

gMoveDescription_FakeTears:: @ 8487BBF
	.string "The user feigns\ncrying to sharply\nlower the foe's\nSP. DEF stat.$"

gMoveDescription_AirCutter:: @ 8487BFF
	.string "The foe is hit with\nrazor-like wind.\nIt has a high\ncritical-hit ratio.$"

gMoveDescription_Overheat:: @ 8487C46
	.string "An intense attack\nthat also sharply\nreduces the user's\nSP. ATK stat.$"

gMoveDescription_OdorSleuth:: @ 8487C8B
	.string "Completely negates\nthe foe's efforts to\nheighten its ability\nto evade.$"

gMoveDescription_RockTomb:: @ 8487CD2
	.string "Boulders are hurled\nat the foe. It also\nlowers the foe's\nSPEED if it hits.$"

gMoveDescription_SilverWind:: @ 8487D1D
	.string "The foe is attacked\nwith a silver dust.\nIt may raise all\nthe user's stats.$"

gMoveDescription_MetalSound:: @ 8487D68
	.string "A horrible metallic\nscreech is used to\nsharply lower the\nfoe's SP. DEF.$"

gMoveDescription_GrassWhistle:: @ 8487DB0
	.string "A pleasant melody\nis played to lull\nthe foe into a deep\nsleep.$"

gMoveDescription_Tickle:: @ 8487DEF
	.string "The foe is made to\nlaugh, reducing its\nATTACK and DEFENSE\nstats.$"

gMoveDescription_CosmicPower:: @ 8487E30
	.string "The user absorbs a\nmystic power to\nraise its DEFENSE\nand SP. DEF.$"

gMoveDescription_WaterSpout:: @ 8487E72
	.string "The higher the\nuser's HP, the more\npowerful this\nattack becomes.$"

gMoveDescription_SignalBeam:: @ 8487EB3
	.string "The foe is hit with\na flashing beam\nthat may also\ncause confusion.$"

gMoveDescription_ShadowPunch:: @ 8487EF6
	.string "The user throws a\npunch from the\nshadows. It cannot\nbe evaded.$"

gMoveDescription_Extrasensory:: @ 8487F35
	.string "The user attacks\nwith an odd power\nthat may make the\nfoe flinch.$"

gMoveDescription_SkyUppercut:: @ 8487F76
	.string "The user attacks\nwith an uppercut\nthrown skywards\nwith force.$"

gMoveDescription_SandTomb:: @ 8487FB4
	.string "The foe is trapped\ninside a whirling\nsandstorm for two\nto five turns.$"

gMoveDescription_SheerCold:: @ 8487FF9
	.string "The foe is attacked\nwith ultimate cold\nthat causes fainting\nif it hits.$"

gMoveDescription_MuddyWater:: @ 8488041
	.string "The user attacks\nwith muddy water.\nIt may also lower\nthe foe's accuracy.$"

gMoveDescription_BulletSeed:: @ 848808A
	.string "The user shoots\nseeds at the foe.\nTwo to five seeds\nare shot at once.$"

gMoveDescription_AerialAce:: @ 84880D0
	.string "An extremely fast\nattack against one\ntarget. It can't be\nevaded.$"

gMoveDescription_IcicleSpear:: @ 8488111
	.string "Sharp icicles are\nfired at the foe.\nIt strikes two to\nfive times.$"

gMoveDescription_IronDefense:: @ 8488153
	.string "The user hardens\nits body's surface\nto sharply raise its\nDEFENSE stat.$"

gMoveDescription_Block:: @ 848819A
	.string "The user blocks the\nfoe's way with arms\nspread wide to\nprevent escape.$"

gMoveDescription_Howl:: @ 84881E1
	.string "The user howls to\nraise its spirit and\nboost its ATTACK\nstat.$"

gMoveDescription_DragonClaw:: @ 848821F
	.string "Sharp, huge claws\nhook and slash the\nfoe quickly and\nwith great power.$"

gMoveDescription_FrenzyPlant:: @ 8488266
	.string "The foe is hit with\nan enormous branch.\nThe user can't move\non the next turn.$"

gMoveDescription_BulkUp:: @ 84882B4
	.string "The user bulks up\nits body to boost\nboth its ATTACK and\nDEFENSE stats.$"

gMoveDescription_Bounce:: @ 84882FB
	.string "The user bounces\non the foe on the\n2nd turn. It may\nparalyze the foe.$"

gMoveDescription_MudShot:: @ 8488341
	.string "The user attacks by\nhurling mud.\nIt also reduces the\nfoe's SPEED.$"

gMoveDescription_PoisonTail:: @ 8488383
	.string "An attack with a\nhigh critical-hit\nratio. It may also\npoison the foe.$"

gMoveDescription_Covet:: @ 84883C9
	.string "A cutely executed\nattack that also\nsteals the foe's\nhold item.$"

gMoveDescription_VoltTackle:: @ 8488408
	.string "The user throws an\nelectrified tackle.\nIt hurts the user\na little.$"

gMoveDescription_MagicalLeaf:: @ 848844B
	.string "The foe is attacked\nwith a strange leaf\nthat cannot be\nevaded.$"

gMoveDescription_WaterSport:: @ 848848A
	.string "Weakens FIRE-type\nattacks while the\nuser is in the\nbattle.$"

gMoveDescription_CalmMind:: @ 84884C5
	.string "The user focuses\nits mind to raise\nthe SP. ATK and\nSP. DEF stats.$"

gMoveDescription_LeafBlade:: @ 8488507
	.string "The foe is slashed\nwith a sharp leaf.\nIt has a high\ncritical-hit ratio.$"

gMoveDescription_DragonDance:: @ 848854F
	.string "A mystic, powerful\ndance that boosts\nthe user's ATTACK\nand SPEED stats.$"

gMoveDescription_RockBlast:: @ 8488597
	.string "The user hurls two\nto five hard rocks\nat the foe to\nattack.$"

gMoveDescription_ShockWave:: @ 84885D3
	.string "A rapid jolt of\nelectricity strikes\nthe foe. It can't\nbe evaded.$"

gMoveDescription_WaterPulse:: @ 8488614
	.string "An attack with a\npulsing blast of\nwater. It may also\nconfuse the foe.$"

gMoveDescription_DoomDesire:: @ 848865A
	.string "A move that attacks\nthe foe with a\nblast of light two\nturns after use.$"

gMoveDescription_PsychoBoost:: @ 84886A1
	.string "An intense attack\nthat also sharply\nreduces the user's\nSP. ATK stat.$"

gROOSTDescription:
    .string "Restores the user's HP by\nhalf of its max HP.$"

gGRAVITYDescription:
   .string "Gravity is intensified\nnegating levitation.$"

gMIRACLE_EYEDescription:
   .string "Makes GHOSTS and evasive\nfoes easier to hit.$"

gWAKE_UP_SLAPDescription:
   .string "Powerful against sleeping\nfoes, but also heals them.$"

gHAMMER_ARMDescription:
   .string "A swinging fist attack\nthat also lowers Speed.$"

gGYRO_BALLDescription:
   .string "A high-speed spin that does\nmore damage to faster foes.$"

gHEALING_WISHDescription:
   .string "The user faints to heal up\nthe recipient.$"

gBRINEDescription:
   .string "Does double damage to foes\nwith half HP.$"

gNATURAL_GIFTDescription:
   .string "The effectiveness varies\nwith the held Berry.$"

gFEINTDescription:
   .string "An attack that hits foes\nusing moves like Protect.$"

gPLUCKDescription:
   .string "Eats the foe's held Berry\ngaining its effect.$"

gTAILWINDDescription:
   .string "Whips up a turbulent breeze\nthat raises Speed.$"

gACUPRESSUREDescription:
   .string "The user sharply raises\none of its stats.$"

gMETAL_BURSTDescription:
   .string "Retaliates any hit with\ngreater power.$"


gU_TURNDescription:
   .string "Does damage then switches\nout the user.$"

gCLOSE_COMBATDescription:
   .string "A strong attack but lowers\nthe defensive stats.$"

gPAYBACKDescription:
   .string "An attack that gains power\nif the user moves last.$"

gASSURANCEDescription:
   .string "An attack that gains power\nif the foe has been hurt.$"

gEMBARGODescription:
   .string "Prevents the foe from\nusing any items.$"

gFLINGDescription:
   .string "The effectiveness varies\nwith the held item.$"

gPSYCHO_SHIFTDescription:
   .string "Transfers status problems\nto the foe.$"

gTRUMP_CARDDescription:
   .string "The less PP the move has\nthe more damage it does.$"

gHEAL_BLOCKDescription:
   .string "Prevents the foe from\nrecovering any HP.$"

gWRING_OUTDescription:
   .string "The higher the foe's HP\nthe more damage caused.$"

gPOWER_TRICKDescription:
   .string "The user swaps its Attack\nand Defense stats.$"

gGASTRO_ACIDDescription:
   .string "Stomach acid suppresses\nthe foe's ability.$"

gLUCKY_CHANTDescription:
   .string "Prevents the foe from\nlanding critical hits.$"

gME_FIRSTDescription:
   .string "Executes the foe's attack\nwith greater power.$"

gCOPYCATDescription:
   .string "The user mimics the last\nmove used by a foe.$"

gPOWER_SWAPDescription:
   .string "Swaps changes to Attack\nand Sp. Atk with the foe.$"

gGUARD_SWAPDescription:
   .string "Swaps changes to Defense\nand Sp. Def with the foe.$"

gPUNISHMENTDescription:
   .string "Does more damage if the\nfoe has powered up.$"

gLAST_RESORTDescription:
   .string "Can only be used if every\nother move has been used.$"

gWORRY_SEEDDescription:
   .string "Plants a seed on the foe\ngiving it Insomnia.$"

gSUCKER_PUNCHDescription:
   .string "Strikes first if the foe\nis preparing an attack.$"

gTOXIC_SPIKESDescription:
   .string "Sets spikes that poison a\nfoe switching in.$"

gHEART_SWAPDescription:
   .string "Swaps any stat changes\nwith the foe.$"

gAQUA_RINGDescription:
   .string "Forms a veil of water\nthat restores HP.$"

gMAGNET_RISEDescription:
   .string "The user levitates with\nelectromagnetism.$"

gFLARE_BLITZDescription:
   .string "A charge that may burn the\nfoe. Also hurts the user.$"

gFORCE_PALMDescription:
   .string "A shock wave attack that\nmay paralyze the foe.$"

gAURA_SPHEREDescription:
   .string "Attacks with an aura blast\nthat cannot be evaded.$"

gROCK_POLISHDescription:
   .string "Polishes the body to\nsharply raise Speed.$"

gPOISON_JABDescription:
   .string "A stabbing attack that\nmay poison the foe.$"

gDARK_PULSEDescription:
   .string "Attacks with a horrible\naura.\nMay cause flinching.$"

gNIGHT_SLASHDescription:
   .string "Hits as soon as possible.\nHigh critical-hit ratio.$"

gAQUA_TAILDescription:
   .string "The user swings its tail\nlike a wave to attack.$"

gSEED_BOMBDescription:
   .string "A barrage of hard seeds\nis fired at the foe.$"

gAIR_SLASHDescription:
   .string "Attacks with a blade of\nair.\nMay cause flinching.$"

gX_SCISSORDescription:
   .string "Slashes the foe with crossed\nscythes, claws, etc.$"

gBUG_BUZZDescription:
   .string "A damaging sound wave that\nmay lower Sp. Def.$"

gDRAGON_PULSEDescription:
   .string "Generates a shock wave to\ndamage the foe.$"

gDRAGON_RUSHDescription:
   .string "Tackles the foe with menace.\nMay cause flinching.$"

gPOWER_GEMDescription:
   .string "Attacks with rays of light\nthat sparkle like diamonds.$"

gVACUUM_WAVEDescription:
   .string "Whirls its fists to send\na wave that strikes first.$"

gFOCUS_BLASTDescription:
   .string "Attacks at full power.\nMay lower Sp. Def.$"

gENERGY_BALLDescription:
   .string "Draws power from nature to\nattack.\nMay lower Sp. Def.$"

gBRAVE_BIRDDescription:
   .string "A low altitude charge that\nalso hurts the user.$"

gEARTH_POWERDescription:
   .string "Makes the ground erupt with\npower.\nMay lower Sp. Def.$"

gSWITCHEROODescription:
   .string "Swaps items with the foe\nfaster than the eye can see.$"

gNASTY_PLOTDescription:
   .string "Thinks bad thoughts to\nsharply boost Sp. Atk.$"

gBULLET_PUNCHDescription:
   .string "Punches as fast as a bul-\nlet.\nIt always hits first.$"

gICE_SHARDDescription:
   .string "Hurls a chunk of ice that\nalways strike first.$"

gSHADOW_CLAWDescription:
   .string "Strikes with a shadow claw.\nHigh critical-hit ratio.$"

gTHUNDER_FANGDescription:
   .string "May cause flinching or\nleave the foe paralyzed.$"

gICE_FANGDescription:
   .string "May cause flinching or\nleave the foe frozen.$"

gFIRE_FANGDescription:
   .string "May cause flinching or\nleave the foe with a burn.$"

gSHADOW_SNEAKDescription:
   .string "Extends the user's shadow\nto strike first.$"

gMUD_BOMBDescription:
   .string "Throws a blob of mud to\ndamage and cut accuracy.$"

gPSYCHO_CUTDescription:
   .string "Tears with psychic blades.\nHigh critical-hit ratio.$"

gZEN_HEADBUTTDescription:
   .string "Hits with a strong head-\nbutt.\nMay cause flinching.$"

gMIRROR_SHOTDescription:
   .string "Emits a flash of energy to\ndamage and cut accuracy.$"

gFLASH_CANNONDescription:
   .string "Releases a blast of light\nthat may lower Sp. Def.$"

gROCK_CLIMBDescription:
   .string "A charging attack that may\nconfuse the foe.$"

gDEFOGDescription:
   .string "Removes obstacles and\nlowers evasion.$"

gTRICK_ROOMDescription:
   .string "Slower POKéMON get to move\nfirst for 5 turns.$"

gDRACO_METEORDescription:
   .string "Casts comets onto the foe.\nHarshly lowers the Sp. Atk.$"

gDISCHARGEDescription:
   .string "Zaps the foes with electri-\ncity.\nMay paralyze them.$"

gPOWER_WHIPDescription:
   .string "Violently lashes the foe\nwith vines or tentacles.$"

gCROSS_POISONDescription:
   .string "A slash that may poison a\nfoe and do critical damage.$"

gGUNK_SHOTDescription:
   .string "Shoots filthy garbage at\nthe foe.\nMay also poison.$"

gIRON_HEADDescription:
   .string "Slams the foe with a hard\nhead.\nMay cause flinching.$"

gMAGNET_BOMBDescription:
   .string "Launches a magnet that\nstrikes without fail.$"

gSTONE_EDGEDescription:
   .string "Stabs the foe with stones.\nHigh critical-hit ratio.$"

gCAPTIVATEDescription:
   .string "Makes the opposite gender\nsharply reduce its Sp. Atk.$"

gSTEALTH_ROCKDescription:
   .string "Sets floating stones that\nhurt a foe switching in.$"

gGRASS_KNOTDescription:
   .string "A snare attack that does\nmore damage to heavier foes.$"

gCHATTERDescription:
   .string "Attacks with a sound wave\nthat causes confusion.$"

gJUDGMENTDescription:
   .string "The type varies with the\nkind of Plate held.$"

gCHARGE_BEAMDescription:
   .string "Fires a beam of electricity.\nMay raise Sp. Atk.$"

gWOOD_HAMMERDescription:
   .string "Slams the body into a foe\nThe user gets hurt too.$"

gAQUA_JETDescription:
   .string "Strikes first by dashing\nat the foe at a high speed.$"

gATTACK_ORDERDescription:
   .string "Underlings pummel the foe.\nHigh critical-hit ratio.$"

gDEFEND_ORDERDescription:
   .string "Raises Defense and Sp. Def\nwith a living shield.$"

gHEAL_ORDERDescription:
   .string "The user's underlings show\nup to heal half its max HP.$"

gHEAD_SMASHDescription:
   .string "A life-risking headbutt that\nseriously hurts the user.$"

gDOUBLE_HITDescription:
   .string "Slams the foe with a tail\netc. Strikes twice.$"

gROAR_OF_TIMEDescription:
   .string "Powerful, but leaves the\nuser immobile the next turn.$"

gSPACIAL_RENDDescription:
   .string "Tears the foe, and space.\nHigh critical-hit ratio.$"

gMAGMA_STORMDescription:
   .string "Traps the foe in a vortex\nof fire for 2 to 5 turns.$"

gDARK_VOIDDescription:
   .string "Drags the foe into total\ndarkness, inducing Sleep.$"

gSEED_FLAREDescription:
   .string "Generates a shock wave that\nsharply reduces Sp. Def.$"

gOMINOUS_WINDDescription:
   .string "A repulsive attack that may\nraise all stats.$"

gSHADOW_FORCEDescription:
   .string "Vanishes on the first turn\nthen strikes the next turn.$"

gHONE_CLAWSDescription:
   .string "Sharpens its claws to raise\nAttack and Accuracy.$"

gWIDE_GUARDDescription:
   .string "Evades wide-ranging attacks\nfor one turn.$"

gGUARD_SPLITDescription:
   .string "Averages changes to Defense\nand Sp. Def with the foe.$"

gPOWER_SPLITDescription:
   .string "Averages changes to Attack\nand Sp. Atk with the foe.$"

gWONDER_ROOMDescription:
   .string "Defense and Sp. Def stats\nare swapped for 5 turns.$"

gPSYSHOCKDescription:
   .string "Attacks with a psychic wave\nthat does physical damage.$"

gVENOSHOCKDescription:
   .string "Does double damage if the\nfoe is poisoned.$"

gAUTOTOMIZEDescription:
   .string "Sheds additional weight to\nsharply boost Speed.$"

gRAGE_POWDERDescription:
   .string "Scatters powder to make\nfoes attack only the user.$"

gTELEKINESISDescription:
   .string "Makes the foe float. It is\neasier to hit for 3 turns.$"

gMAGIC_ROOMDescription:
   .string "Hold items lose their\neffects for 5 turns.$"

gSMACK_DOWNDescription:
   .string "Throws a rock to knock the\nfoe down to the ground.$"

gSTORM_THROWDescription:
   .string "This attack always results\nin a critical hit.$"

gFLAME_BURSTDescription:
   .string "A bursting flame that does\ndamage to all foes.$"

gSLUDGE_WAVEDescription:
   .string "Swamps the foe with a wave\nof sludge\nMay also poison.$"

gQUIVER_DANCEDescription:
   .string "Dances to raise Sp. Atk\nSp. Def and Speed.$"

gHEAVY_SLAMDescription:
   .string "Does more damage if the\nuser outweighs the foe.$"

gSYNCHRONOISEDescription:
   .string "An odd shock wave that only\ndamages same-type foes.$"

gELECTRO_BALLDescription:
   .string "Hurls an orb that does more\ndamage to slower foes.$"

gSOAKDescription:
   .string "Sprays water at the foe\nmaking it Water-type.$"

gFLAME_CHARGEDescription:
   .string "Attacks in a cloak of\nflames. Raises Speed.$"

gCOILDescription:
   .string "Coils up to raise Attack\nDefense and Accuracy.$"

gLOW_SWEEPDescription:
   .string "Attacks the foe's legs\nlowering its Speed.$"

gACID_SPRAYDescription:
   .string "Sprays a hide-melting acid.\nSharply reduces Sp. Def.$"

gFOUL_PLAYDescription:
   .string "The higher the foe's Attack\nthe more damage caused.$"

gSIMPLE_BEAMDescription:
   .string "A beam that changes the\nfoe's ability to Simple.$"

gENTRAINMENTDescription:
   .string "Makes the foe mimic the\nuser, gaining its ability.$"

gAFTER_YOUDescription:
   .string "Helps out the foe, letting\nit move next.$"

gROUNDDescription:
   .string "A song that inflicts damage.\nOthers can join in too.$"

gECHOED_VOICEDescription:
   .string "Does more damage every turn\nit is used.$"

gCHIP_AWAYDescription:
   .string "Strikes through the foe's\nstat changes.$"

gCLEAR_SMOGDescription:
   .string "Attacks with white haze that\neliminates all stat changes.$"

gSTORED_POWERDescription:
   .string "The higher the user's stats\nthe more damage caused.$"

gQUICK_GUARDDescription:
   .string "Evades priority attacks\nfor one turn.$"

gALLY_SWITCHDescription:
   .string "The user switches places\nwith its partner.$"

gSCALDDescription:
   .string "Shoots boiling water at the\nfoe.\nMay inflict a burn.$"

gSHELL_SMASHDescription:
   .string "Raises offensive stats, but\nlowers defensive stats.$"

gHEAL_PULSEDescription:
   .string "Recovers up to half the\ntarget's maximum HP.$"

gHEXDescription:
   .string "Does double damage if the\nfoe has a status problem.$"

gSKY_DROPDescription:
   .string "Takes the foe into the sky\nthen drops it the next turn.$"

gSHIFT_GEARDescription:
   .string "Rotates its gears to raise\nAttack and Speed.$"

gCIRCLE_THROWDescription:
   .string "Knocks the foe away to end\nthe battle.$"

gINCINERATEDescription:
   .string "Burns up Berries and Gems\npreventing their use.$"

gQUASHDescription:
   .string "Suppresses the foe, making\nit move last.$"

gACROBATICSDescription:
   .string "Does double damage if the\nuser has no item.$"

gREFLECT_TYPEDescription:
   .string "The user reflects the foe's\ntype, copying it.$"

gRETALIATEDescription:
   .string "An attack that does more\ndamage if an ally fainted.$"

gFINAL_GAMBITDescription:
   .string "The user faints to damage\nthe foe equal to its HP.$"

gBESTOWDescription:
   .string "The user gives its held\nitem to the foe.$"

gINFERNODescription:
   .string "Powerful and sure to inflict\na burn, but inaccurate.$"

gWATER_PLEDGEDescription:
   .string "Attacks with a column of\nwater\nMay make a rainbow.$"

gFIRE_PLEDGEDescription:
   .string "Attacks with a column of\nfire\nMay burn the grass.$"

gGRASS_PLEDGEDescription:
   .string "Attacks with a column of\ngrass\nMay create a swamp.$"

gSTRUGGLE_BUGDescription:
   .string "Resisting, the user attacks\nthe foe. Lowers Sp. Atk.$"

gBULLDOZEDescription:
   .string "Stomps down on the ground.\nLowers Speed.$"

gWORK_UPDescription:
   .string "The user is roused.\nUps Attack and Sp. Atk.$"

gELECTROWEBDescription:
   .string "Snares the foe with an\nelectric net.\nLowers Speed.$"

gWILD_CHARGEDescription:
   .string "An electrical tackle that\nalso hurts the user.$"

gDRILL_RUNDescription:
   .string "Spins its body like a drill.\nHigh critical-hit ratio.$"

gDUAL_CHOPDescription:
   .string "Attacks with brutal hits\nthat strike twice.$"

gHEART_STAMPDescription:
   .string "A sudden blow after a cute\nact.\nMay cause flinching.$"

gRAZOR_SHELLDescription:
   .string "Tears at the foe with sharp\nshells\nMay lower Defense.$"

gLEAF_TORNADODescription:
   .string "Circles the foe with leaves\nto damage and cut accuracy.$"

gSTEAMROLLERDescription:
   .string "Crushes the foe with its\nbody.\nMay cause flinching.$"

gCOTTON_GUARDDescription:
   .string "Wraps its body in cotton.\nDrastically raises Defense.$"

gNIGHT_DAZEDescription:
   .string "Looses a pitch-black\nshockwave\nMay lower accuracy.$"

gTAIL_SLAPDescription:
   .string "Strikes the foe with its\ntail 2 to 5 times.$"

gHURRICANEDescription:
   .string "Traps the foe in a fierce\nwind.\nMay cause confusion.$"

gHEAD_CHARGEDescription:
   .string "A charge using guard hair.\nIt hurts the user a little.$"

gGEAR_GRINDDescription:
   .string "Throws two steel gears\nthat strike twice.$"

gTECHNO_BLASTDescription:
   .string "The type varies with the\nkind of Drive held.$"

gRELIC_SONGDescription:
   .string "Attacks with an ancient\nsong\nMay induce sleep.$"

gSECRET_SWORDDescription:
   .string "Cuts with a long horn that\ndoes physical damage.$"

gGLACIATEDescription:
   .string "Blows very cold air at the\nfoe. It lowers their Speed.$"

gBOLT_STRIKEDescription:
   .string "Strikes with a great amount\nof lightning\nMay paralyze.$"

gBLUE_FLAREDescription:
   .string "Engulfs the foe in a blue\nflame.\nMay inflict a burn.$"

gFIERY_DANCEDescription:
   .string "Dances cloaked in flames.\nMay raise Sp. Atk.$"

gFREEZE_SHOCKDescription:
   .string "A powerful 2-turn move that\nmay paralyze the foe.$"

gICE_BURNDescription:
   .string "A powerful 2-turn move that\nmay inflict a burn.$"

gSNARLDescription:
   .string "Yells and rants at the foe\nlowering its Sp. Atk.$"

gICICLE_CRASHDescription:
   .string "Drops large icicles on the\nfoe.\nMay cause flinching.$"

gV_CREATEDescription:
   .string "Very powerful, but lowers\nDefense, Sp. Def and Speed.$"

gFUSION_FLAREDescription:
   .string "Summons a fireball. Works\nwell with a thunderbolt.$"

gFUSION_BOLTDescription:
   .string "Summons a thunderbolt.\nWorks well with a fireball.$"

gFLYING_PRESSDescription:
   .string "This attack does Fighting\nand Flying-type damage.$"

gMAT_BLOCKDescription:
   .string "Evades damaging moves\nfor one turn.$"

gBELCHDescription:
   .string "Lets out a loud belch.\nMust eat a Berry to use it.$"

gROTOTILLERDescription:
   .string "Ups the Attack and Sp. Atk\nof Grass-type POKéMON.$"

gSTICKY_WEBDescription:
   .string "Weaves a sticky net that\nslows foes switching in.$"

gFELL_STINGERDescription:
   .string "If it knocks out a foe\nthe Attack stat is raised.$"

gTRICK_OR_TREATDescription:
   .string "Goes trick-or-treating\nmaking the foe Ghost-type.$"

gNOBLE_ROARDescription:
   .string "Intimidates the foe, to cut\nAttack and Sp. Atk.$"

gION_DELUGEDescription:
   .string "Electrifies Normal-type\nmoves with charged atoms.$"

gPARABOLIC_CHARGEDescription:
   .string "Damages adjacent Pokémon and\nheals up by half of it.$"

gFORESTS_CURSEDescription:
   .string "Puts a curse on the foe\nmaking the foe Grass-type.$"

gPETAL_BLIZZARDDescription:
   .string "Stirs up a violent storm\nof petals to attack.$"

gFREEZE_DRYDescription:
   .string "Super effective\non Water-types.\nMay cause freezing.$"

gDISARMING_VOICEDescription:
   .string "Lets out a charming cry\nthat cannot be evaded.$"

gPARTING_SHOTDescription:
   .string "Lowers the foe's Attack and\nSp. Atk, then switches out.$"

gTOPSY_TURVYDescription:
   .string "Swaps all stat changes that\naffect the target.$"

gDRAINING_KISSDescription:
   .string "An attack that absorbs over\nhalf the damage inflicted.$"

gCRAFTY_SHIELDDescription:
   .string "Evades status moves for\none turn.$"

gFLOWER_SHIELDDescription:
   .string "Raises the Defense of\nGrass-type POKéMON.$"

gGRASSY_TERRAINDescription:
   .string "The ground turns to grass\nfor 5 turns. Restores HP.$"

gMISTY_TERRAINDescription:
   .string "Covers the ground with mist\nfor 5 turns. Blocks status.$"

gELECTRIFYDescription:
   .string "Electrifies the foe, making\nits next move Electric-type.$"

gPLAY_ROUGHDescription:
   .string "Plays rough with the foe.\nMay lower Attack.$"

gFAIRY_WINDDescription:
   .string "Stirs up a fairy wind to\nstrike the foe.$"

gMOONBLASTDescription:
   .string "Attacks with the power of\nthe moon\nMay lower Sp. Atk.$"

gBOOMBURSTDescription:
   .string "Attacks everything with a\ndestructive sound wave.$"

gFAIRY_LOCKDescription:
   .string "Locks down the battlefield\npreventing escape next turn.$"

gKINGS_SHIELDDescription:
   .string "Evades damage, and sharply\nreduces Attack if struck.$"

gPLAY_NICEDescription:
   .string "Befriend the foe, lowering\nits Attack without fail.$"

gCONFIDEDescription:
   .string "Shares a secret with the\nfoe, lowering Sp. Atk.$"

gDIAMOND_STORMDescription:
   .string "Whips up a storm of\ndiamonds\nMay up Defense.$"

gSTEAM_ERUPTIONDescription:
   .string "Immerses the foe in heated\nsteam.\nMay inflict a burn.$"

gHYPERSPACE_HOLEDescription:
   .string "Uses a warp hole to attack.\nCan't be evaded.$"

gWATER_SHURIKENDescription:
   .string "Throws 2 to 5 stars that\nare sure to strike first.$"

gMYSTICAL_FIREDescription:
   .string "Breathes a special, hot\nfire\nMay lower Sp. Atk.$"

gSPIKY_SHIELDDescription:
   .string "Evades attack, and damages\nthe foe if struck.$"

gAROMATIC_MISTDescription:
   .string "Raises the Sp. Def of a\npartner POKéMON.$"

gEERIE_IMPULSEDescription:
   .string "Exposes the foe to a pulse\nthat sharply cuts Sp. Atk.$"

gVENOM_DRENCHDescription:
   .string "Lowers the Attack, Sp. Atk\nand Speed of a poisoned foe.$"

gPOWDERDescription:
   .string "Damages the foe if it uses\na Fire-type move.$"

gGEOMANCYDescription:
   .string "Raises Sp. Atk, Sp. Def and\nSpeed on the 2nd turn.$"

gMAGNETIC_FLUXDescription:
   .string "Boosts the defenses of\nthose with Plus or Minus.$"

gHAPPY_HOURDescription:
   .string "Doubles the amount of\nPrize Money received.$"

gELECTRIC_TERRAINDescription:
   .string "Electrifies the ground for\n5 turns. Prevents sleep.$"

gDAZZLING_GLEAMDescription:
   .string "Damages foes by emitting\na bright flash.$"

gCELEBRATEDescription:
   .string "Congratulates you on your\nspecial day.$"

gHOLD_HANDSDescription:
   .string "The user and ally hold hands\nmaking them happy.$"

gBABYDOLL_EYESDescription:
   .string "Lowers the foe's Attack\nbefore it can move.$"

gNUZZLEDescription:
   .string "Rubs its cheecks against\nthe foe, paralyzing it.$"

gINFESTATIONDescription:
   .string "The foe is infested and\nattacked for 2 to 5 turns.$"

gPOWER_UP_PUNCHDescription:
   .string "A hard punch that raises\nthe user's Attack.$"

gTHOUSAND_ARROWSDescription:
   .string "Can hit Flying foes, then\nknocks them to the ground.$"

gTHOUSAND_WAVESDescription:
   .string "Those hit by the wave can\nno longer escape.$"

gLANDS_WRATHDescription:
   .string "Gathers the energy of the\nland to attack every foe.$"

gLIGHT_OF_RUINDescription:
   .string "Fires a great beam of light\nthat also hurts the user.$"

gORIGIN_PULSEDescription:
   .string "Beams of glowing blue light\nblast both foes.$"

gPRECIPICE_BLADESDescription:
   .string "Fearsome blades of stone\nattack both foes.$"

gLAVA_PLUMEDescription:
   .string "Scarlet flames torch\neverything around the user.$"

gLEAF_STORMDescription:
   .string "Whips up a storm of leaves.\nHarshly lowers the Sp. Atk.$"

gSHORE_UPDescription:
   .string "Restores the user's HP.\nMore HP in a sandstorm.$"

gFIRST_IMPRESSIONDescription:
   .string "Hits hard and first.\nOnly works first turn.$"

gBANEFUL_BUNKERDescription:
   .string "Protects user and poisons\nfoes on contact.$"

gSPIRIT_SHACKLEDescription:
   .string "After being hit, foes can\nno longer escape.$"

gDARKEST_LARIATDescription:
   .string "Swings the arms to strike\nIt ignores stat changes.$"

gSPARKLING_ARIADescription:
   .string "Sings with bubbles. Cures\nburns on contact.$"

gICE_HAMMERDescription:
   .string "Swings the fist to strike.\nLowers the user's SPEED.$"

gFLORAL_HEALINGDescription:
   .string "Restores an ally's HP.\nHeals more on grass.$"

gHIGH_HORSEPOWERDescription:
   .string "Slams hard into the foe with\nits entire body.$"

gSTRENGTH_SAPDescription:
   .string "Saps the foe's Attack to\nheal HP, then drops Attack.$"

gSOLAR_BLADEDescription:
   .string "Charges first turn, then\nchops with a blade of light.$"

gLEAFAGEDescription:
   .string "Attacks with a flurry of\nsmall leaves.$"

gSPOTLIGHTDescription:
   .string "Makes the foe attack the\nspotlighted POKéMON.$"

gTOXIC_THREADDescription:
   .string "Attacks with a thread that\npoisons and drops Speed.$"

gLASER_FOCUSDescription:
   .string "Guarantees the next move\nwill be a critical hit.$"

gGEAR_UPDescription:
   .string "Boosts the attacks of\nthose with Plus or Minus.$"

gTHROAT_CHOPDescription:
   .string "Chops the throat to disable\nsound moves for a while.$"

gPOLLEN_PUFFDescription:
   .string "Explodes on foes, but\nrestores ally's HP.$"

gANCHOR_SHOTDescription:
   .string "Strangles the foe with a\nchain. The foe can't flinch.$"

gPSYCHIC_TERRAINDescription:
   .string "The ground turns weird for\n5 turns. Blocks priority.$"

gLUNGEDescription:
   .string "Lunges at the foe to lower\nits Attack stat.$"

gFIRE_LASHDescription:
   .string "Whips the foe with fire\nlowering its Defense.$"

gPOWER_TRIPDescription:
   .string "It hits harder the more\nstat boosts the user has.$"

gBURN_UPDescription:
   .string "Burns out the user fully\nremoving the Fire type.$"

gSPEED_SWAPDescription:
   .string "Swaps user's Speed with\nthe target's.$"

gSMART_STRIKEDescription:
   .string "Hits with an accurate\nhorn that never misses.$"

gPURIFYDescription:
   .string "Cures the foe's status\nto restore HP.$"

gREVELATION_DANCEDescription:
   .string "Dances with mystical power.\nMatches user's first type.$"

gCORE_ENFORCERDescription:
   .string "Hits with a ray that\nnullifies the foe's ability.$"

gTROP_KICKDescription:
   .string "An intense kick from the\ntropics. Lowers Attack.$"

gINSTRUCTDescription:
   .string "Orders the target to use\nits last move again.$"

gBEAK_BLASTDescription:
   .string "Heats up beak to attack.\nBurns foe on contact.$"

gCLANGING_SCALESDescription:
   .string "Makes a big noise with\nits scales. Drops Defense.$"

gDRAGON_HAMMERDescription:
   .string "Swings its whole body\nlike a hammer to damage.$"

gBRUTAL_SWINGDescription:
   .string "Violently swings around\nto hurt everyone nearby.$"

gAURORA_VEILDescription:
   .string "Weakens all attacks, but\nonly usable with hail.$"

gSHELL_TRAPDescription:
   .string "Sets a shell trap that\ndamages on contact.$"

gFLEUR_CANNONDescription:
   .string "A strong ray that harshly\nlowers Sp. Attack.$"

gPSYCHIC_FANGSDescription:
   .string "Chomps with psychic fangs.\nDestroys any barriers.$"

gSTOMPING_TANTRUMDescription:
   .string "Stomps around angrily.\nStronger after a failure.$"

gSHADOW_BONEDescription:
   .string "Strikes with a haunted\nbone. Might drop Defense.$"

gACCELEROCKDescription:
   .string "Hits with a high-speed\nrock that always goes first.$"

gLIQUIDATIONDescription:
   .string "Slams the foe with water.\nCan lower Defense.$"

gPRISMATIC_LASERDescription:
   .string "A high power laser that\nforces recharge next turn.$"

gSPECTRAL_THIEFDescription:
   .string "Steals the target's stat\nboosts, then attacks.$"

gSUNSTEEL_STRIKEDescription:
   .string "A sun-fueled strike that\nignores abilities.$"

gMOONGEIST_BEAMDescription:
   .string "A moon-powered beam that\nignores abilities.$"

gTEARFUL_LOOKDescription:
   .string "The user tears up, dropping\nAttack and Sp. Attack.$"

gZING_ZAPDescription:
   .string "An electrified impact that\ncan cause flinching.$"

gNATURES_MADNESSDescription:
   .string "Halves the foe's HP with\nthe power of nature.$"

gMULTI_ATTACKDescription:
   .string "An attack that changes\nwith Memories.$"

gMIND_BLOWNDescription:
   .string "It explodes the user's head\nto damage everything around.$"

gPLASMA_FISTSDescription:
   .string "Hits with electrical fists.\nNormal moves become Electric.$"

gPHOTON_GEYSERDescription:
   .string "User's highest attack stat\ndetermines its category.$"

gZIPPY_ZAPDescription:
   .string "Electric bursts always go\nfirst and land a critical hit.$"

gSPLISHY_SPLASHDescription:
   .string "A huge electrified wave that\nmay paralyze the foe.$"

gFLOATY_FALLDescription:
   .string "Floats in air and dives at\nangle.\nMay cause flinching.$"

gPIKA_PAPOWDescription:
   .string "Pikachu's love increases its\npower. It never misses.$"

gBOUNCY_BUBBLEDescription:
   .string "An attack that absorbs\nall the damage inflicted.$"


gBUZZY_BUZZDescription:
   .string "Shoots a jolt of electricity\nthat always paralyzes.$"

gSIZZLY_SLIDEDescription:
   .string "User cloaked in fire charges.\nLeaves the foe with a burn.$"

gGLITZY_GLOWDescription:
   .string "Telekinetic force that sets\nwall, lowering Sp. Atk damage.$"

gBADDY_BADDescription:
   .string "Acting badly, attacks. Sets\nwall, lowering Attack damage.$"

gSAPPY_SEEDDescription:
   .string "Giant stalk scatters seeds\nthat drain HP every turn.$"

@change to potentially also have 30% freeze chance but lower pp
gFREEZY_FROSTDescription:
   .string "Crystal from cold haze hits.\nEliminates all stat changes.$"

gSPARKLY_SWIRLDescription:
   .string "Wrap foe with whirlwind of\nscent. Heals party's status.$"

gVEEVEE_VOLLEYDescription:
   .string "Eevee's love increases its\npower. It never misses.$"

gDOUBLE_IRON_BASHDescription:
   .string "The user spins and hits with\nits arms.\nMay cause flinch.$"
    
// GEN 8
gDYNAMAX_CANNONDescription:
   .string "Fires a strong beam. Deals\n2x damage to Dynamaxed foes.$"
    
gSNIPE_SHOTDescription:
   .string "The user ignores effects\nthat draw in moves.$"
    
gJAW_LOCKDescription:
   .string "Prevents the user and\nthe target from escaping.$"
    
gSTUFF_CHEEKSDescription:
   .string "Consumes the user's Berry,\nthen sharply raises Def.$"
    
gNO_RETREATDescription:
   .string "Raises all of the user's\nstats but prevents escape.$"
    
gTAR_SHOTDescription:
   .string "Lowers the foe's Speed and\nmakes it weak to Fire.$"
    
gMAGIC_POWDERDescription:
   .string "Magic powder changes the\ntarget into a Psychic-type.$"
    
gDRAGON_DARTSDescription:
   .string "The user attacks twice. Two\ntargets are hit once each.$"
    
gTEATIMEDescription:
   .string "All Pokémon have teatime\nand eat their Berries.$"
    
gOCTOLOCKDescription:
   .string "Traps the foe to lower Def\nand Sp. Def fall each turn.$"
    
gBOLT_BEAKDescription:
   .string "Double power if the user\nmoves before the target.$"
    
gFISHIOUS_RENDDescription:
   .string "Double power if the user\nmoves before the target.$"
    
gCOURT_CHANGEDescription:
   .string "The user swaps effects on\neither side of the field.$"
    
gCLANGOROUS_SOULDescription:
   .string "The user uses some of its\nHP to raise all its stats.$"
    
gBODY_PRESSDescription:
   .string "Does more damage the\nhigher the user's Def.$"
    
gDECORATEDescription:
   .string "The user sharply raises\nthe target's Atk and Sp.Atk$"
    
gDRUM_BEATINGDescription:
   .string "Plays a drum to attack.\nThe foe's Speed is lowered.$"
    
gSNAP_TRAPDescription:
   .string "Snares the target in a snap\ntrap for four to five turns.$"
    
gPYRO_BALLDescription:
   .string "Launches a fiery ball at the\ntarget. It may cause a burn.$"
    
gBEHEMOTH_BLADEDescription:
   .string "Strikes as a sword. It deals\n2x damage to Dynamaxed foes.$"
    
gBEHEMOTH_BASHDescription:
   .string "Attacks as a sheild. Deals\n2x damage to Dynamaxed foes.$"
    
gAURA_WHEELDescription:
   .string "Raises Speed to attack. The\nType is based on its form.$"
    
gBREAKING_SWIPEDescription:
   .string "Swings its tail to attack.\nLowers the Atk of those hit.$"
    
gBRANCH_POKEDescription:
   .string "The user pokes the target\nwith a pointed branch.$"
    
gOVERDRIVEDescription:
   .string "The user twangs its guitar,\ncausing strong vibrations.$"
    
gAPPLE_ACIDDescription:
   .string "Attacks with tart apple acid\nto lower the foe's Sp. Def.$"
    
gGRAV_APPLEDescription:
   .string "Drops an apple from above.\nLowers the foe's Defense.$"
    
gSPIRIT_BREAKDescription:
   .string "Attacks with spirit-breaking\nforce. Lowers Sp. Atk.$"
    
gSTRANGE_STEAMDescription:
   .string "Emits a strange steam to\npotentially confuse the foe.$"
    
gLIFE_DEWDescription:
   .string "Scatters water to restore\nthe HP of itself and allies.$"
    
gOBSTRUCTDescription:
   .string "Protects itself, harshly\nlowering Def on contact.$"
    
gFALSE_SURRENDERDescription:
   .string "Bows to stab the foe\nwith hair. It never misses.$"
    
gMETEOR_ASSAULTDescription:
   .string "Attacks with a thick leek.\nThe user must then rest.$"
    
gETERNABEAMDescription:
   .string "Eternatus' strongest move.\nThe user rests next turn.$"
    
gSTEEL_BEAMDescription:
   .string "Fires a beam of steel from\nits body. It hurts the user.$"

gEXPANDING_FORCEDescription:
   .string "Power goes up and damages\nall foes on Psychic Terrain.$"

gSTEEL_ROLLERDescription:
   .string "Destroys terrain. Fails if\nground isn't terrain.$"

gSCALE_SHOTDescription:
   .string "Shoots scales 2 to 5 times.\nUps Speed, lowers defense.$"

gMETEOR_BEAMDescription:
   .string "A 2-turn move that raises\nSp. Attack before attacking.$"

gSHELL_SIDE_ARMDescription:
   .string "Uses higher of physical and\nspecial damage\nMay poison.$"

gMISTY_EXPLOSIONDescription:
   .string "Hit everything and faint.\nPowers up on Misty Terrain.$"

gGRASSY_GLIDEDescription:
   .string "Gliding on ground, hits. Goes\nfirst on Grassy Terrain.$"

gRISING_VOLTAGEDescription:
   .string "This move's power doubles\nwhen on Electric Terrain.$"

gTERRAIN_PULSEDescription:
   .string "Type and power changes\ndepending on the terrain.$"

gSKITTER_SMACKDescription:
   .string "User skitters behind foe to\nattack. Lowers foe's Sp. Atk.$"

gBURNING_JEALOUSYDescription:
   .string "Foes that have stats upped\nduring the turn get burned.$"

gLASH_OUTDescription:
   .string "If stats lowered during this\nturn, power is doubled.$"

gPOLTERGEISTDescription:
   .string "Control foe's item to attack.\nFails if foe has no item.$"

gCORROSIVE_GASDescription:
   .string "Highly acidic gas melts items\nheld by surrounding Pokémon.$"

gCOACHINGDescription:
   .string "Properly coaches allies to\nup their Attack and Defense.$"

gFLIP_TURNDescription:
   .string "Attacks and rushes back to\nswitch with a party Pokémon.$"

gTRIPLE_AXELDescription:
   .string "A 3-kick attack that gets\nmore powerful with each hit.$"

gDUAL_WINGBEATDescription:
   .string "User slams the target with\nwings and hits twice in a row.$"

gSCORCHING_SANDSDescription:
   .string "Throws scorching sand at\nthe target\nMay leave a burn.$"

gJUNGLE_HEALINGDescription:
   .string "Heals HP and status of\nitself and allies in battle.$"

gWICKED_BLOWDescription:
   .string "Mastering the Dark style,\nstrikes with a critical hit.$"

gSURGING_STRIKESDescription:
   .string "Mastering the Water style,\nstrikes with 3 critical hits.$"

gTHUNDER_CAGEDescription:
   .string "Traps the foe in a cage of\nelectricity for 2 to 5 turns.$"

gDRAGON_ENERGYDescription:
   .string "The higher the user's HP\nthe more damage caused.$"

gFREEZING_GLAREDescription:
   .string "Shoots psychic power from\nthe eyes\nMay freeze the foe.$"

gFIERY_WRATHDescription:
   .string "An attack fueled by your\nwrath.\nMay cause flinching.$"

gTHUNDEROUS_KICKDescription:
   .string "Uses a lightning-like kick\nto hit. Lowers foe's Defense.$"

gGLACIAL_LANCEDescription:
   .string "Strikes by hurling a blizzard-\ncloaked icicle lance at a foe.$"

gASTRAL_BARRAGEDescription:
   .string "Strikes by sending a frightful\namount of ghosts at a foe.$"

gEERIE_SPELLDescription:
   .string "Attacks with psychic power.\nFoe's last move has 3 PP cut.$"

gMoveDescription_Cocoon:
   .string "Not done yet.$"

gMoveDescription_Monotype:
   .string "Not done yet.$"

gMoveDescription_FlashFreeze:
	.string "Instantly freezes\nthe foe with a\ngust of sub-zero wind.$"

gMoveDescription_DryadsCurse:
	.string "Sacrifices stats\nto curse the last foe\nwho attacked the user.$"

gMoveDescription_ShieldBash:
	.string "The user blocks its body\nwith a shield, and\ncounters if hit with\na physical move\ndamage is based on DEF.$"

gUP_ROOTDescription:
   .string "Does damage then switches\nout the user.$"

gDIVE_BOMBDescription:	@can add on to thesee 2
   .string "Does damage then switches\nout the user.$"

gNETTLE_VINEDescription:  @name tbd
	.string "Attacks the target\nwith a vine covered\nin Nettle bristles.\nIf not a GRASS type,\nIt may leave the\nfoe with a burn.$"

@can hold 5 line breaks given current space post expansion! at approx 20 chars per line@ 
@would like to port to a .h file like abilities  actually updated red repo uses .c for this and works perfect will update to that soon
